import type { CarapaceConfig, ActionLog, LogStats } from './types';

export const DEFAULT_CONFIG: CarapaceConfig = {
  security: {
    keyRotationMinutes: 30,
    spendingLimits: {
      perAction: 50,
      daily: 200,
      warnAbove: 20,
    },
    contacts: {
      mode: 'blocklist',
      allowed: [],
      blocked: ['spam@malicious.com'],
    },
    domains: {
      mode: 'blocklist',
      allowed: [],
      blocked: ['malware-site.xyz'],
    },
    blockedActions: ['install_package'],
    customRules: [
      {
        if: { field: 'amount', operator: 'greater_than', value: 100 },
        then: 'block',
        reason: 'Purchases over $100 require manual approval',
      },
    ],
  },
  anchor: {
    refreshIntervalMinutes: 15,
    goals: [
      'Complete Q4 financial report by end of week',
      'Respond to all pending client emails',
      'Review and approve team pull requests',
    ],
    priorities: [
      { rank: 1, text: 'Client deliverables take precedence over internal tasks' },
      { rank: 2, text: 'Security reviews cannot be postponed' },
      { rank: 3, text: 'Documentation updates are lowest priority' },
    ],
    constraints: [
      'Never share API keys or credentials externally',
      'Do not modify production databases directly',
      'All financial transactions over $50 require confirmation',
    ],
    context:
      'Preparing for Thursday board meeting. Focus on Q4 data and scheduling prep time.',
    goalCategories: ['email', 'productivity', 'finance', 'coding'],
  },
  monitoring: {
    logRetentionDays: 30,
    alertOnUnverifiedTier1: true,
    maxActionsBeforeAnchor: 20,
  },
};

const SESSION_ID = 'sess_a7f3b2c1';

const now = Date.now();
const minute = 60 * 1000;

export const MOCK_ACTIONS: ActionLog[] = [
  {
    id: 1,
    timestamp: new Date(now - 2 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'send_email',
    target: 'john.smith@clientcorp.com',
    amount: 0,
    description: 'Sent Q4 report summary to client stakeholder',
    verdict: 'pass',
    reason: 'Action within configured limits',
    key_was_valid: true,
    tier: 2,
    created_at: new Date(now - 2 * minute).toISOString(),
  },
  {
    id: 2,
    timestamp: new Date(now - 5 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'make_purchase',
    target: 'AWS Infrastructure - us-east-1',
    amount: 47.5,
    description: 'Provisioned additional EC2 instance for load testing',
    verdict: 'pass',
    reason: 'Amount within per-action limit',
    key_was_valid: true,
    tier: 1,
    created_at: new Date(now - 5 * minute).toISOString(),
  },
  {
    id: 3,
    timestamp: new Date(now - 12 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'delete_file',
    target: '/var/logs/archive/2024-q3-old.tar.gz',
    amount: 0,
    description: 'Attempted to delete archived log file',
    verdict: 'block',
    reason: 'Delete operations on archive directory are restricted',
    key_was_valid: true,
    tier: 1,
    created_at: new Date(now - 12 * minute).toISOString(),
  },
  {
    id: 4,
    timestamp: new Date(now - 18 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'browse_new_domain',
    target: 'https://docs.newframework.io',
    amount: 0,
    description: 'Browsing documentation for new framework evaluation',
    verdict: 'pass',
    reason: 'Domain not in blocklist',
    key_was_valid: true,
    tier: 3,
    created_at: new Date(now - 18 * minute).toISOString(),
  },
  {
    id: 5,
    timestamp: new Date(now - 25 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'api_write',
    target: 'POST /api/v2/deployments',
    amount: 0,
    description: 'Triggered staging deployment via CI/CD pipeline',
    verdict: 'pass',
    reason: 'API write to staging environment allowed',
    key_was_valid: true,
    tier: 1,
    created_at: new Date(now - 25 * minute).toISOString(),
  },
  {
    id: 6,
    timestamp: new Date(now - 35 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'send_message',
    target: '#engineering-team (Slack)',
    amount: 0,
    description: 'Posted deployment notification to team channel',
    verdict: 'pass',
    reason: 'Internal communication channel allowed',
    key_was_valid: true,
    tier: 3,
    created_at: new Date(now - 35 * minute).toISOString(),
  },
  {
    id: 7,
    timestamp: new Date(now - 42 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'make_purchase',
    target: 'GitHub Copilot Enterprise - Annual',
    amount: 234.0,
    description: 'Attempted purchase of annual Copilot license',
    verdict: 'block',
    reason: 'Amount $234.00 exceeds custom rule limit of $100',
    key_was_valid: true,
    tier: 1,
    created_at: new Date(now - 42 * minute).toISOString(),
  },
  {
    id: 8,
    timestamp: new Date(now - 55 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'file_write',
    target: '/home/user/projects/dashboard/src/config.ts',
    amount: 0,
    description: 'Updated configuration file with new API endpoints',
    verdict: 'pass',
    reason: 'File write to project directory allowed',
    key_was_valid: true,
    tier: 2,
    created_at: new Date(now - 55 * minute).toISOString(),
  },
  {
    id: 9,
    timestamp: new Date(now - 68 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'shell_command',
    target: 'npm run build && npm run test',
    amount: 0,
    description: 'Running build and test pipeline locally',
    verdict: 'warn',
    reason: 'Shell commands flagged for review',
    key_was_valid: false,
    tier: 1,
    created_at: new Date(now - 68 * minute).toISOString(),
  },
  {
    id: 10,
    timestamp: new Date(now - 78 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'calendar_modify',
    target: 'Board Meeting - Thursday 2:00 PM',
    amount: 0,
    description: 'Rescheduled board meeting from 3 PM to 2 PM',
    verdict: 'pass',
    reason: 'Calendar modification within allowed scope',
    key_was_valid: true,
    tier: 2,
    created_at: new Date(now - 78 * minute).toISOString(),
  },
  {
    id: 11,
    timestamp: new Date(now - 95 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'send_email',
    target: 'team@company.com',
    amount: 0,
    description: 'Sent weekly standup summary to engineering team',
    verdict: 'pass',
    reason: 'Internal email allowed',
    key_was_valid: true,
    tier: 3,
    created_at: new Date(now - 95 * minute).toISOString(),
  },
  {
    id: 12,
    timestamp: new Date(now - 110 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'install_package',
    target: 'npm install suspicious-pkg@latest',
    amount: 0,
    description: 'Attempted to install unverified npm package',
    verdict: 'block',
    reason: 'install_package is in blocked action types',
    key_was_valid: true,
    tier: 1,
    created_at: new Date(now - 110 * minute).toISOString(),
  },
  {
    id: 13,
    timestamp: new Date(now - 125 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'browse_new_domain',
    target: 'https://stackoverflow.com/questions/react-hooks',
    amount: 0,
    description: 'Researching React hooks patterns for dashboard',
    verdict: 'pass',
    reason: 'Domain not in blocklist',
    key_was_valid: true,
    tier: 3,
    created_at: new Date(now - 125 * minute).toISOString(),
  },
  {
    id: 14,
    timestamp: new Date(now - 140 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'account_change',
    target: 'AWS IAM - production-deployer role',
    amount: 0,
    description: 'Attempted to modify IAM role permissions',
    verdict: 'block',
    reason: 'Account changes to production IAM roles require manual approval',
    key_was_valid: false,
    tier: 1,
    created_at: new Date(now - 140 * minute).toISOString(),
  },
  {
    id: 15,
    timestamp: new Date(now - 160 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'make_purchase',
    target: 'Vercel Pro Plan - Monthly',
    amount: 20.0,
    description: 'Monthly Vercel hosting subscription renewal',
    verdict: 'warn',
    reason: 'Amount equals warning threshold of $20',
    key_was_valid: true,
    tier: 2,
    created_at: new Date(now - 160 * minute).toISOString(),
  },
  {
    id: 16,
    timestamp: new Date(now - 180 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'file_write',
    target: '/home/user/.ssh/config',
    amount: 0,
    description: 'Attempted to modify SSH configuration',
    verdict: 'block',
    reason: 'Writes to .ssh directory are blocked by security policy',
    key_was_valid: true,
    tier: 1,
    created_at: new Date(now - 180 * minute).toISOString(),
  },
  {
    id: 17,
    timestamp: new Date(now - 200 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'send_email',
    target: 'hr@company.com',
    amount: 0,
    description: 'Forwarded PTO request to HR department',
    verdict: 'pass',
    reason: 'Internal email allowed',
    key_was_valid: true,
    tier: 3,
    created_at: new Date(now - 200 * minute).toISOString(),
  },
  {
    id: 18,
    timestamp: new Date(now - 220 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'api_write',
    target: 'PUT /api/v2/config/feature-flags',
    amount: 0,
    description: 'Toggled beta feature flag for dashboard v2',
    verdict: 'pass',
    reason: 'Feature flag updates on staging allowed',
    key_was_valid: true,
    tier: 2,
    created_at: new Date(now - 220 * minute).toISOString(),
  },
  {
    id: 19,
    timestamp: new Date(now - 245 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'shell_command',
    target: 'docker compose up -d',
    amount: 0,
    description: 'Started local development environment containers',
    verdict: 'pass',
    reason: 'Docker commands in development context allowed',
    key_was_valid: true,
    tier: 2,
    created_at: new Date(now - 245 * minute).toISOString(),
  },
  {
    id: 20,
    timestamp: new Date(now - 270 * minute).toISOString(),
    session_id: SESSION_ID,
    action_type: 'browse_new_domain',
    target: 'https://malware-site.xyz/download',
    amount: 0,
    description: 'Attempted to browse blocked domain',
    verdict: 'block',
    reason: 'Domain malware-site.xyz is in blocklist',
    key_was_valid: true,
    tier: 1,
    created_at: new Date(now - 270 * minute).toISOString(),
  },
];

export const MOCK_STATS: LogStats = {
  totalActions: MOCK_ACTIONS.length,
  sessionActions: MOCK_ACTIONS.length,
  verifiedCount: MOCK_ACTIONS.filter((a) => a.key_was_valid).length,
  unverifiedCount: MOCK_ACTIONS.filter((a) => !a.key_was_valid).length,
  blockedCount: MOCK_ACTIONS.filter((a) => a.verdict === 'block').length,
  unverifiedTier1Count: MOCK_ACTIONS.filter(
    (a) => !a.key_was_valid && a.tier === 1
  ).length,
  tierBreakdown: {
    t1: MOCK_ACTIONS.filter((a) => a.tier === 1).length,
    t2: MOCK_ACTIONS.filter((a) => a.tier === 2).length,
    t3: MOCK_ACTIONS.filter((a) => a.tier === 3).length,
  },
  dailySpend: MOCK_ACTIONS.reduce((sum, a) => sum + a.amount, 0),
};
